version: '3'
services:
  app:
    build: .
    ports:
    - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=1234
  db:
   image: postgres
   environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=mydb