version: '3'
services:

  database:
   image: postgres
   environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=mydb
   volumes:
    - postgres-data:/var/lib/postgresql/data
    
  springboot:
    build: .
    ports:
    - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - database
      
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - springboot

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email leonardo.ciurcau@stud.ubbcluj.ro --agree-tos --no-eff-email -d labsdi-shop.mooo.com

volumes:
  postgres-data:
  certbot-etc:
  certbot-var: