version: '3'
services:

  database:
   image: postgres:15
   environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=mydb
   volumes:
    - /var/lib/postgresql/14/main:/var/lib/postgresql/15/main
    
  springboot:
    build: .
    ports:
    - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mydb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - database